services:
  server-php-aev3:
    container_name: servidor_php_aev3
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    stdin_open: true
    links:
      - mariadb-server-aev3
    ports:
      - "8030:8000"
    volumes:
      - ../:/var/www/html:delegated
    networks:
      - project_network

  mariadb-server-aev3:
    container_name: servidor_db_aev3
    image: mariadb
    ports:
      - "3330:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - project_network

volumes:
  db_mysql:

networks:
  project_network: