lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_PRIVATE_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 7200
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
