lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    passphrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 7200

    token_extractors:
        cookie:
            enabled: true
            name: BEARER
